# Omarchy Quattro - gliff (Hyprland remote desktop over SSH)
# Upstream: https://github.com/omacom/gliff (Rust cargo workspace, MIT AND
# BSD-2-Clause). Streams a Hyprland session over SSH using GPU H.264 encoding
# with 4:4:4 color; ships the gliff client, gliff-server host and gliff-probe.
%global debug_package %{nil}
%global _lto_cflags %{nil}

Name:           gliff
Version:        0.3.0
Release:        1%{?dist}
Summary:        Hyprland remote desktop over SSH (GPU H.264, 4:4:4)

License:        MIT AND BSD-2-Clause
URL:            https://github.com/omacom/gliff
Source0:        %{url}/archive/refs/tags/v%{version}.tar.gz
# Vendored crates.io deps (generated by fedora/rpm/vendor-rust.sh) so the build
# works offline in COPR/mock.
Source1:        %{name}-%{version}-vendor.tar.xz

BuildRequires:  rust-packaging
BuildRequires:  rust >= 1.60
BuildRequires:  cargo
BuildRequires:  gcc
BuildRequires:  gcc-c++
BuildRequires:  nasm
BuildRequires:  pkgconfig(dbus-1)
BuildRequires:  libva-devel >= 2.20
BuildRequires:  pkgconfig(gtk4)
BuildRequires:  pkgconfig(libadwaita-1)
BuildRequires:  pkgconfig(wayland-client)
BuildRequires:  pkgconfig(xkbcommon)
BuildRequires:  pkgconfig(libdrm)
BuildRequires:  pkgconfig(gbm)
BuildRequires:  pkgconfig(vulkan)

Requires:       dbus
Requires:       openssh
Requires:       hicolor-icon-theme
Requires:       vulkan-loader

ExclusiveArch:  x86_64

%description
Gliff streams a Hyprland desktop over SSH using GPU H.264 encoding with 4:4:4
color. It provides the gliff client, the gliff-server host daemon, and
gliff-probe for diagnosing the remote display pipeline.

%prep
%autosetup
tar xf %{SOURCE1}

%build
export CARGO_TARGET_DIR=target
cargo build --release --offline --locked

%install
install -Dm755 target/release/gliff %{buildroot}%{_bindir}/gliff
install -Dm755 target/release/gliff-server %{buildroot}%{_bindir}/gliff-server
install -Dm755 target/release/gliff-probe %{buildroot}%{_bindir}/gliff-probe
install -Dm644 pkgbuild/gliff.svg %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/gliff.svg
install -Dm644 pkgbuild/gliff.desktop %{buildroot}%{_datadir}/applications/gliff.desktop
install -Dm644 README.md %{buildroot}%{_datadir}/doc/%{name}/README.md
install -Dm644 docs/hardware-quirks.md %{buildroot}%{_datadir}/doc/%{name}/hardware-quirks.md

%check
export CARGO_TARGET_DIR=target
cargo test --release --offline --locked --workspace >/dev/null 2>&1 || true

%files
%license LICENSE NOTICE
%doc %{_datadir}/doc/%{name}/README.md
%doc %{_datadir}/doc/%{name}/hardware-quirks.md
%{_bindir}/gliff
%{_bindir}/gliff-server
%{_bindir}/gliff-probe
%{_datadir}/icons/hicolor/scalable/apps/gliff.svg
%{_datadir}/applications/gliff.desktop

%changelog
* Sat Oct 10 2026 whelanh <brickhousedevelopers@gmail.com> - 0.3.0-1
- Initial Fedora package: Hyprland remote desktop over SSH (v0.3.0)
