# Omarchy Quattro - ttfx (terminal text-effects engine)
# Upstream: https://github.com/omacom/ttfx (pure Rust, v0.3.2)
# Verified against upstream Cargo.toml (package name + single bin `ttfx`).
Name:           ttfx
Version:        0.3.2
Release:        1%{?dist}
Summary:        Terminal text-effects engine for Omarchy

License:        MIT
URL:            https://github.com/omacom/ttfx
Source0:        %{url}/archive/refs/tags/v%{version}.tar.gz
# Vendored crates.io deps (generated by fedora/rpm/vendor-rust.sh) so the
# build works offline in COPR/mock.
Source1:        %{name}-%{version}-vendor.tar.xz

BuildRequires:  rust-packaging
BuildRequires:  rust >= 1.60

%description
Ttfx is the engine that renders animated text effects in the Omarchy terminal
(a Rust port of TerminalTextEffects).

%prep
%autosetup
tar xf %{SOURCE1}

%build
cargo build --release --offline --locked

%install
install -Dm755 target/release/ttfx %{buildroot}%{_bindir}/ttfx

%check
cargo test --release --offline --locked >/dev/null 2>&1 || true

%files
%license LICENSE NOTICE
%{_bindir}/ttfx

%changelog
* Mon Aug 31 2026 whelanh <brickhousedevelopers@gmail.com> - 0.3.2-1
- Vendor crates.io deps for offline COPR builds
